apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.helloApp.name }}
  labels:
    app: {{ .Values.helloApp.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.helloApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.helloApp.name }}
        version: "1.0.0"
    spec:
      containers:
        - name: {{ .Values.helloApp.name }}
          image: strm/helloworld-http
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloApp.name }}
  labels:
    app: {{ .Values.helloApp.name }}
spec:
  selector:
    app: {{ .Values.helloApp.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
